const orders = [
  {
    id: 1,
    image: "https://via.placeholder.com/100",
    customerName: "John Doe",
    quantity: 2,
    price: 60.25,
    totalAmount: 120.5,
    orderDate: "2024-12-14",
    orderStatus: "pending",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/100",
    customerName: "Jane Smith",
    quantity: 1,
    price: 89.99,
    totalAmount: 89.99,
    orderDate: "2024-12-13",
    orderStatus: "pending",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/100",
    customerName: "Ali Ahmed",
    quantity: 4,
    price: 50.0,
    totalAmount: 200.0,
    orderDate: "2024-12-12",
    orderStatus: "completed",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/100",
    customerName: "Sara Khan",
    quantity: 3,
    price: 15.0,
    totalAmount: 45.0,
    orderDate: "2024-12-11",
    orderStatus: "cancelled",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/100",
    customerName: "Michael Brown",
    quantity: 5,
    price: 30.15,
    totalAmount: 150.75,
    orderDate: "2024-12-10",
    orderStatus: "completed",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/100",
    customerName: "Emily Davis",
    quantity: 1,
    price: 300.0,
    totalAmount: 300.0,
    orderDate: "2024-12-09",
    orderStatus: "pending",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/100",
    customerName: "David Wilson",
    quantity: 2,
    price: 80.0,
    totalAmount: 160.0,
    orderDate: "2024-12-08",
    orderStatus: "completed",
  },
  {
    id: 8,
    image: "https://via.placeholder.com/100",
    customerName: "Sophia Lopez",
    quantity: 3,
    price: 45.0,
    totalAmount: 135.0,
    orderDate: "2024-12-07",
    orderStatus: "cancelled",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/100",
    customerName: "William Johnson",
    quantity: 4,
    price: 22.5,
    totalAmount: 90.0,
    orderDate: "2024-12-06",
    orderStatus: "completed",
  },
  {
    id: 10,
    image: "https://via.placeholder.com/100",
    customerName: "Olivia Martinez",
    quantity: 2,
    price: 75.0,
    totalAmount: 150.0,
    orderDate: "2024-12-05",
    orderStatus: "pending",
  },
  {
    id: 11,
    image: "https://via.placeholder.com/100",
    customerName: "James White",
    quantity: 6,
    price: 15.0,
    totalAmount: 90.0,
    orderDate: "2024-12-04",
    orderStatus: "pending",
  },
  {
    id: 12,
    image: "https://via.placeholder.com/100",
    customerName: "Mia Hernandez",
    quantity: 1,
    price: 120.0,
    totalAmount: 120.0,
    orderDate: "2024-12-03",
    orderStatus: "completed",
  },
  {
    id: 13,
    image: "https://via.placeholder.com/100",
    customerName: "Lucas Green",
    quantity: 5,
    price: 30.0,
    totalAmount: 150.0,
    orderDate: "2024-12-02",
    orderStatus: "cancelled",
  },
  {
    id: 14,
    image: "https://via.placeholder.com/100",
    customerName: "Ella Scott",
    quantity: 2,
    price: 70.0,
    totalAmount: 140.0,
    orderDate: "2024-12-01",
    orderStatus: "completed",
  },
  {
    id: 15,
    image: "https://via.placeholder.com/100",
    customerName: "Benjamin Allen",
    quantity: 3,
    price: 25.0,
    totalAmount: 75.0,
    orderDate: "2024-11-30",
    orderStatus: "pending",
  },
  {
    id: 16,
    image: "https://via.placeholder.com/100",
    customerName: "Amelia Clark",
    quantity: 4,
    price: 20.0,
    totalAmount: 80.0,
    orderDate: "2024-11-29",
    orderStatus: "completed",
  },
  {
    id: 17,
    image: "https://via.placeholder.com/100",
    customerName: "Jack King",
    quantity: 3,
    price: 50.0,
    totalAmount: 150.0,
    orderDate: "2024-11-28",
    orderStatus: "cancelled",
  },
  {
    id: 18,
    image: "https://via.placeholder.com/100",
    customerName: "Lily Wright",
    quantity: 1,
    price: 200.0,
    totalAmount: 200.0,
    orderDate: "2024-11-27",
    orderStatus: "pending",
  },
  {
    id: 19,
    image: "https://via.placeholder.com/100",
    customerName: "Henry Hill",
    quantity: 2,
    price: 90.0,
    totalAmount: 180.0,
    orderDate: "2024-11-26",
    orderStatus: "completed",
  },
  {
    id: 20,
    image: "https://via.placeholder.com/100",
    customerName: "Charlotte Torres",
    quantity: 4,
    price: 40.0,
    totalAmount: 160.0,
    orderDate: "2024-11-25",
    orderStatus: "completed",
  },
];

export default orders;
